  query Home {
    home {
      data {

        attributes {
          introtext
          introsubtext
          hero {
            data {
              attributes {
                url
              }
            }
          }
        }
      }
    }
  }
