    query ($limit: Int) {
      projects(pagination: { limit: $limit }) {
        data {
          id
          attributes {
            title
            image {
              data {
                attributes {
                  url
                  alternativeText
                }
              }
            }
          }
        }
      }
    }
