  query {
    projects {
      data {
        id
        attributes {
          title
          overview
          url
          image {
            data {
              attributes {
                url
              }
            }
          }
          technologies {
            data {
              id
              attributes {
                name
              }
            }
          }
        }
      }
    }
  }
