  query Articles($id: ID!) {
    article(id: $id) {
      data {
        id
        attributes {
          publishedAt
          title
          content
          image {
            data {
              attributes {
                url
                alternativeText
              }
            }
          }
          categories {
            data {
              id
              attributes {
                name
              }
            }
          }
        }
      }
    }
  }
