    query ($limit: Int) {
      articles(pagination: { limit: $limit }) {
        data {
          id
          attributes {
            title
            content
            image {
              data {
                attributes {
                  url
                  alternativeText
                }
              }
            }
            categories {
              data {
                id
                attributes {
                  name
                }
              }
            }
          }
        }
      }
    }
