    query {
      articles {
        data {
          id
          attributes {
            title
            content
            image {
              data {
                attributes {
                  url
                }
              }
            }
            categories {
              data {
                id
                attributes {
                  name
                }
              }
            }
          }
        }
      }
    }
