  query {
    blogs {
      data {
        id
        attributes {
          title
          content
          heroimage {
            data {
              attributes {
                url
              }
            }
          }
          categories {
            data {
              id
              attributes {
                name
              }
            }
          }
        }
      }
    }
  }
